apiVersion: v1
data:
  .env.production: |
    EXTERNAL_URL=https://mxb.cc
    MONGO_URI=mongodb://username:password@mongo-service:27017/database
    REDIS_HOST=redis-service
    SESSION_STORE=mongo

    NETEASE_PHONE=
    NETEASE_PASSWORD=
    NETEASE_COUNTRY_CODE=86
    SING_USERNAME=
    SING_PASSWORD=

    MAILER_HOST=smtp.qq.com
    MAILER_USER=
    MAILER_PASS=
    MAILER_NAME=MXB

    ALI_ACCESS_KEY=
    ALI_SECRET_KEY=
    ALI_REGION=oss-cn-beijing
    ALI_BUCKET=mxbcc

    TENCENT_SECRET_ID=
    TENCENT_SECRET_KEY=
    CAPTCHA_APP_ID=
    CAPTCHA_SECRET_KEY=
kind: ConfigMap
metadata:
  name: api-mxb-cc-configmap
  namespace: default
